version: "3.7"

networks:
  local:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecocare-app
    working_dir: /var/www/html
    restart: unless-stopped
    networks:
      - local
    ports:
      - 8000:80
      - 8100:433
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:8.0
    hostname: mysql
    container_name: ecocare-mysql
    networks:
      - local
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: ecocare
      MYSQL_DATABASE: management
      MYSQL_ROOT_PASSWORD: ecocare
    command: mysqld --sql_mode=""
    volumes:
      - ./database:/var/lib/

  adminer:
    image: adminer
    container_name: ecocare-adminer
    restart: always
    networks:
      - local
    ports:
      - 8080:8080
